# Generated by Django 5.0.1 on 2024-02-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=50)),
                ('campaign_tagline', models.CharField(max_length=500)),
                ('campaign_venue', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=10000)),
                ('desc2', models.CharField(default='', max_length=10000)),
                ('campaign_date', models.DateField()),
                ('campaign_image', models.FileField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('prod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.campaign')),
            ],
        ),
    ]
